<a href="https://colab.research.google.com/github/kartiksharma2383/Machine-Learning/blob/main/Random_Forest_in_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
import pandas as pd
import numpy as np
import seaborn as sns

In [81]:
df = pd.read_csv('/content/penguins(ML - Random Forest dataset).csv')
df

Unnamed: 0    species     island  bill_length_mm  bill_depth_mm  \
0             1     Adelie  Torgersen            39.1           18.7   
1             2     Adelie  Torgersen            39.5           17.4   
2             3     Adelie  Torgersen            40.3           18.0   
3             4     Adelie  Torgersen             NaN            NaN   
4             5     Adelie  Torgersen            36.7           19.3   
..          ...        ...        ...             ...            ...   
339         340  Chinstrap      Dream            55.8           19.8   
340         341  Chinstrap      Dream            43.5           18.1   
341         342  Chinstrap      Dream            49.6           18.2   
342         343  Chinstrap      Dream            50.8           19.0   
343         344  Chinstrap      Dream            50.2           18.7   

     flipper_length_mm  body_mass_g     sex  year  
0                181.0       3750.0    male  2007  
1                186.0       3800.0  female  2007  
2                195.0       3250.0  female  2007  
3                  NaN          NaN     NaN  2007  
4                193.0       3450.0  female  2007  
..                 ...          ...     ...   ...  
339              207.0       4000.0    male  2009  
340              202.0       3400.0  female  2009  
341              193.0       3775.0    male  2009  
342              210.0       4100.0    male  2009  
343              198.0       3775.0  female  2009  

[344 rows x 9 columns]

In [82]:
df.shape

(344, 9)

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         344 non-null    int64  
 1   species            344 non-null    object 
 2   island             344 non-null    object 
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object 
 8   year               344 non-null    int64  
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB


In [84]:
df.isnull().sum()

Unnamed: 0            0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [85]:
df.dropna(inplace = True)

In [86]:
df.isnull().sum()

Unnamed: 0           0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

In [87]:
df.sex.unique()

array(['male', 'female'], dtype=object)

In [88]:
pd.get_dummies(df['sex']).head()

female   male
0   False   True
1    True  False
2    True  False
4    True  False
5   False   True

In [89]:
sex = pd.get_dummies(df['sex'], drop_first = True)
sex.head()

male
0   True
1  False
2  False
4  False
5   True

In [90]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [91]:
pd.get_dummies(df['island']).head()

Biscoe  Dream  Torgersen
0   False  False       True
1   False  False       True
2   False  False       True
4   False  False       True
5   False  False       True

In [92]:
island = pd.get_dummies(df['island'], drop_first = True)
island.head()

Dream  Torgersen
0  False       True
1  False       True
2  False       True
4  False       True
5  False       True

In [93]:
# concatenate the above two dataframe to the original df
new_data = pd.concat([df, island, sex], axis = 1)
new_data.head()

Unnamed: 0 species     island  bill_length_mm  bill_depth_mm  \
0           1  Adelie  Torgersen            39.1           18.7   
1           2  Adelie  Torgersen            39.5           17.4   
2           3  Adelie  Torgersen            40.3           18.0   
4           5  Adelie  Torgersen            36.7           19.3   
5           6  Adelie  Torgersen            39.3           20.6   

   flipper_length_mm  body_mass_g     sex  year  Dream  Torgersen   male  
0              181.0       3750.0    male  2007  False       True   True  
1              186.0       3800.0  female  2007  False       True  False  
2              195.0       3250.0  female  2007  False       True  False  
4              193.0       3450.0  female  2007  False       True  False  
5              190.0       3650.0    male  2007  False       True   True

In [94]:
# Drop the repeated column
new_data.drop(['island', 'sex'], axis = 1, inplace = True)
new_data.head()

Unnamed: 0 species  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0           1  Adelie            39.1           18.7              181.0   
1           2  Adelie            39.5           17.4              186.0   
2           3  Adelie            40.3           18.0              195.0   
4           5  Adelie            36.7           19.3              193.0   
5           6  Adelie            39.3           20.6              190.0   

   body_mass_g  year  Dream  Torgersen   male  
0       3750.0  2007  False       True   True  
1       3800.0  2007  False       True  False  
2       3250.0  2007  False       True  False  
4       3450.0  2007  False       True  False  
5       3650.0  2007  False       True   True

In [95]:
new_data.drop(['Unnamed: 0'], axis = 1, inplace = True)
new_data.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   year  Dream  Torgersen   male  
0  2007  False       True   True  
1  2007  False       True  False  
2  2007  False       True  False  
4  2007  False       True  False  
5  2007  False       True   True

In [97]:
y = new_data.species
y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [98]:
y.unique()

array(['Adelie', 'Gentoo', 'Chinstrap'], dtype=object)

In [99]:
# map function is used to convert categorical values into numeric values.
y = y.map({'Adelie':0, 'Chinstrap':1, 'Gentoo':2})
y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [101]:
new_data.drop('species', inplace = True, axis = 1)
new_data.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  year  Dream  \
0            39.1           18.7              181.0       3750.0  2007  False   
1            39.5           17.4              186.0       3800.0  2007  False   
2            40.3           18.0              195.0       3250.0  2007  False   
4            36.7           19.3              193.0       3450.0  2007  False   
5            39.3           20.6              190.0       3650.0  2007  False   

   Torgersen   male  
0       True   True  
1       True  False  
2       True  False  
4       True  False  
5       True   True

In [102]:
x = new_data

In [103]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [105]:
print('x_train', x_train.shape)
print('x_test', x_test.shape)
print('y_train', y_train.shape)
print('y_test', y_test.shape)

x_train (233, 8)
x_test (100, 8)
y_train (233,)
y_test (100,)


In [108]:
# ensemble(It combine the predictions of multiple individual models (often called base estimators) to improve overall performance)
# using entropy criteria
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 5, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [109]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 2, 1, 2, 2, 1, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0,
       1, 2, 1, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 1, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 2, 0, 2, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0,
       2, 2, 2, 1, 2, 2, 1, 2, 0, 1, 0, 1, 0, 2, 2, 2, 2, 1, 2, 2, 2, 0,
       0, 1, 1, 0, 2, 0, 1, 0, 2, 0, 2, 2])

In [110]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score

In [111]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[48,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 34]])

In [112]:
accuracy_score(y_test, y_pred)

1.0

In [113]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        48
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [114]:
# using gini criteria
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 5, criterion = 'gini', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(n_estimators=5, random_state=0)

In [115]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 2, 1, 2, 2, 1, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0,
       1, 2, 1, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 1, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 2, 0, 2, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0,
       2, 2, 2, 1, 2, 2, 1, 2, 0, 1, 0, 1, 0, 2, 2, 2, 2, 1, 2, 2, 2, 0,
       0, 1, 1, 0, 2, 0, 1, 0, 2, 0, 2, 2])

In [116]:
accuracy_score(y_test, y_pred)

1.0